# Generated by Django 5.2.4 on 2025-09-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memo_title", models.CharField(max_length=100)),
                ("memo_content", models.TextField(blank=True)),
            ],
        ),
    ]
