# Generated by Django 5.2.4 on 2025-10-08 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work08", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memo",
            name="memo_image",
            field=models.ImageField(blank=True, null=True, upload_to="memo_images/"),
        ),
    ]
