# Generated by Django 5.2.4 on 2025-10-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work09", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="due_data",
            new_name="due_date",
        ),
    ]
